name: macOS CD

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - run: flutter config --enable-macos-desktop
      - run: flutter build macos
      - name: artifact upload
        uses: actions/upload-artifact@v3
        with:
          name: macos
          path: ./build/macos/
          retention-days: 1
